### ISSUE TITLE
MongoParseError: options usefindandmodify, usecreateindex are not supported

### ISSUE THREAD

**Issue by ksb96** [akashyap2013/CRUD_Application_Node#10]
![Capture-333](https://user-images.githubusercontent.com/52975077/180757909-8dce807c-44a2-4b64-9138-75be7d8119a4.JPG)
![Capture-444](https://user-images.githubusercontent.com/52975077/180757918-8bb3f9bd-4311-412b-bf61-096a5bbbbb31.JPG)
![Capture-1111](https://user-images.githubusercontent.com/52975077/180757920-e89ef508-35ca-43f7-85d7-f852eca0c2dc.JPG)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ankitsaini074** [comment]
install mongoose@5.10.11

**Comment by ksb96** [comment]
> install mongoose@5.10.11

didn't work, but instead of removing "useFindAndModify" & "useCreateIndex", it worked!!
